# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

nginx:
  image:
    repository: gihyodocker/nginx
    tag: latest
    backendHost: localhost:8080
    containerPort: 80

apigw_server_sjoh:
  image:
    repository: sjoh1/apigw-server-sjoh
    tag: 0.0.1
    containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: sjoh1-apigw-server-sjoh
  path: "/"
