# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

nginx:
  image:
    repository: nginx
    tag: stable
    containerPort: 80

demoapp:
  image:
    repository: sjoh1/demoapp
    tag: 0.0.1
    containerPort: 8080

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  host: apigw_server.test
  path: "/"
