# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

nginx:
  image:
    repository: nginx/nginx-ingress
    tag: latest
    backendHost: localhost:8080
    containerPort: 80

demoapp:
  image:
    repository: sjoh1/demoapp
    tag: 0.0.1
    containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: sjoh1-demoapp.local
  path: "/hello"
