apiVersion: v1
kind: Service
metadata:
  name: {{ include "apigw_server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "apigw_server.name" . }}
    helm.sh/chart: {{ include "apigw_server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "apigw_server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
