{{- if .Values.ingress.enabled -}}
{{- $fullName := include "demoapp.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "demoapp.name" . }}
    helm.sh/chart: {{ include "demoapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ include "demoapp.fullname" . }}
          servicePort: {{ .Values.service.port }}
{{- end }}
