apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template: # template 아래는 파드 리소스 정의와 같음
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: nginx
        image: gihyodocker/nginx:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        ports:
        - name: http
        - containerPort: 80
        env:
        - name: BACKEND_HOST
          value: localhost:8080

      - name: echo
        image: gihyodocker/echo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: 8080
