apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apigw-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "apigw-server.name" . }}
    helm.sh/chart: {{ include "apigw-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "apigw-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "apigw-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        env:
        - name: BACKEND_HOST
          value: {{ .Values.nginx.image.backendHost }}
        ports:
        - containerPort: {{ .Values.nginx.image.containerPort }}
      - name: apigw-server
        image: {{ ".Values.apigw-server.image.repository" }}:{{ ".Values.apigw-server.image.tag" }}
        ports:
        - containerPort: {{ ".Values.apigw-server.image.containerPort" }}
